### ISSUE TITLE
commenti nella classe FiltroLibero

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#10]
it.edu.iisgubbio.sostituzioni.filtri.FiltroLibero mancano i commenti standard sopra il nome della classe, anche alcuni che spiegano come funziona non sarebbero male

**Comment by Bianca001** [comment]
questo l'ho fatto io, solo che sto riscontrando qualche problema con Git per caricarlo

**Comment by SoftwareIISGubbio** [comment]
Se ci dici (qui o altrove) quale problema magari qualcuno ti può aiutare.

**Comment by Bianca001** [comment]
Ce l'ho fatta, grazie

**Comment by SoftwareIISGubbio** [comment]
Bianca non farne ulteriori perché i lavori erano per tutta la classe

**Comment by Bianca001** [comment]
Ah scusi non l’avevo capito
