### ISSUE TITLE
commenti nella classe FiltroAPagamento

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#12]
ls classe it.edu.iisgubbio.sostituzioni.filtri.FiltroAPagamento è del tutto senza commenti

**Comment by Cristopsi** [comment]
Aggiunti i commenti nella classe "FiltroAPagamento"  -   Cristian

**Comment by SoftwareIISGubbio** [comment]
commit: 19d239dce99d75eb95534f28ed4b5a72f60c100e
