### ISSUE TITLE
tutti i filtri sono utilizzati?

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#13]
Verificare se tutti i filtri sono stati ustai e se nonn lo sono da capire il perché (se sono stati scritti probabile che servano)

**Comment by GiorgioNonECapace** [comment]
No, non tutti i filtri sono utilizzati, quelli non utilizzati sono  FiltroAPagamento e FiltroOreBuche.
Immagino che non sono stati implementati per questioni di tempo.

**Comment by SoftwareIISGubbio** [comment]
Servono indicazioni su come usarli o... li cancelliamo?

**Comment by GiorgioNonECapace** [comment]
No non sono da cancellare, sono semplicemente da implementare, ma questa issue non chiede di implementarlo quindi non saprei cosa aggiungere...

**Comment by SoftwareIISGubbio** [comment]
Anche questo è giusto.
