### ISSUE TITLE
Leggere i dati da un solo file

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#25]
Bisogna provare a rimuovere la parte che legge anche dal file XML di fet e vedere se funziona tutto. O vedere cosa non va.

Un possibile modfo è creare una classe LettoreFileSingolo che fa esattamente lo stesso lavoro di LettoreFile ma non legge dal file XML.

Per come è costruito it.edu.iisgubbio.sostituzioni.Ambiente il metodo leggiXML() deve esserci magari se non fa niente va benme lo stesso.

**Comment by SoftwareIISGubbio** [comment]
Questo problema da risolvere è articolato: conviene procedere per passi e lavorare su un ramo di sviluppo a se.
il ramo si chiama "fileSingolo" per spostarsi su questo ramo basta "git checkout fileSingolo"
prima di tutto dobbiamo capire quali informazioni mancano nel file excel attuale (scriverle come risposta qui)

**Comment by SoftwareIISGubbio** [comment]
il lavoro su #29 incide su questo

**Comment by riginel** [comment]
Serve il parametro in "insieme_totale" della  materia del professore.
Nel caso si può usare il parametro "gruppo" del foglio "informazioni"

**Comment by SoftwareIISGubbio** [comment]
Attualmente il programma funziona utilizzando il gruppo del docente, il nome della materia ora per ora non c'è nel file excel che usiamo attualmente. commit fc5a45cf49d2ea59e
