### ISSUE TITLE
Mancato uso dei fogli di stile

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#26]
Sarebbe buona cosa avere un foglio di stile unico agganciato al file FXML in modo che le caratteristiche grafiche (ad esempio i colori) siano controllate in un posto unico (e ben leggibile)

**Comment by SoftwareIISGubbio** [comment]
per iniziare prova a vedere auli sono le proprietà chje puoi togliere e scivile qui

**Comment by Davidoscki** [comment]
Finestra Principale:
-fx-background-color: #f4d03f; Background Totale
-fx-background-color: #3B3B3B; Colore Testi
-fx-background-color: white; all'interno di tutti ComboBox

-fx-background-radius: 6 tutti?

**File: Info Docenti**
**Generale**
-fx-background-color: #FFFFDA
Padding  left="10.0" right="10.0" top="10.0"
**Titolo** bottom ="20.0"
**Titoletti (Label)**
    text-align: center-left

**ListViewv**
    -fx-width: 200;
    -fx-height: 200;


TODO: cercare altro

**Comment by SoftwareIISGubbio** [comment]
Le larghezze da valutare se conviene lasxciare nel file FXML o meno, cposì come vgap e hgap, spostare tutto ciò che riguarda font, colori, bordi nel css, agganciarlo a tutti i file FXML, assicurarsi che nei file fxml non ci siano più riferimenti a font, colori, bordi almeno.

**Comment by Davidoscki** [comment]
Problema risolto commit 9f72b7c4470791b158a3bd8bdb8ca20d4a7785c7 e fa6d30b6004e6a99a3e7dc7bc6ea93f12a525dfa
