### ISSUE TITLE
Verificare errori lettura docenti

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#27]
Visualizzando il prof MICANTI ENRICO i dati presentano molti "null" perché ?

**Comment by Phlaveeoh** [comment]
Ho girato quasi un'ora per le varie righe di codice e per il file excel e credo che vengono visualizzati tanti "null" perchè qualche prof sulla parte "docenti" compare, mentre sulla parte "informazioni" no. Forse è questo che causa problemi ma non ne sono sicuro.

**Comment by SoftwareIISGubbio** [comment]
ok, allora lasciamo aperto questo bug e quando avremo delle tabelle più affidabili faremo nuove prove

**Comment by SoftwareIISGubbio** [comment]
Possibile che la spiegazione sia giusta, dal commit a27e778efdcff1bc977786b18 questo problema non si riscontra più.
