### ISSUE TITLE
Finestra informazioni programma non funziona

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#33]
È accessibile dal menu /Opzioni/Informazioni... e attualmente non c'è niente di sensato è soltanto testo statico.

Bisogna fare anche la classe controller it.edi.iisgubbio.sostituzioni.InfoProgramma

Sarebbe bello se la finestra avesse anche uno spazio per contenere un elenco di nomi degli sviluppatori.

Ancora più bello se quei nomi venissero stampati in ordine casuale.

**Comment by SoftwareIISGubbio** [comment]
gli sviluppatori oltre a quelli attuali sono gli studenti dell'attuale 5i

**Comment by Davidoscki** [comment]
Problema finito con i commit a27e778efdcff1bc977786b1828d2a70a2a0a8ff e commit ce59097b625a10c5ed9bb408a1aa8b599b346c3b
