### ISSUE TITLE
docenti liberi è troppo generico, favorire ore buche o simili

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#43]
L'ultima scelta sono i docenti "liberi", sarebbe interessante se "libero" equivalesse a ora buca o al più un'ora prima/dopo rispetto a quelle che già si fanno, bisogna guardare it.edu.iisgubbio.sostituzioni.filtri.FiltroOreBuche che attualmente è inutilizzato.

**Comment by Yoshiro0990** [comment]
Con quale colore deve comparire, e dopo quale tipo di sostituzione?

**Comment by SoftwareIISGubbio** [comment]
per adesso mettiamo questi, poi se non vanno ci faranno sapere.

ora_buca_della_classe  colore: 804d23
ora_buca_altra_classe_stesso_gruppo colore: a76f41
ora_buca_altra_classe_altro_gruppo colore: d6a47a

in fondo prima dei "liberi"

**Comment by Yoshiro0990** [comment]
Aggiunte le motivazioni  ora_buca_della_classe, ora_buca_altra_classe_stesso_gruppo e ora_buca_altra_classe_altro_gruppo con il commit 2d85842
