### ISSUE TITLE
cambiare visualizzazione sostituzione

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#44]
Cambiare la visualizzazione della sostituzione:
Adesso compare così
`vista l'assenza di ALUNNO

Per il giorno lunedì 11 gennaio 2021

CARNEVALI lo sostituirà nella classe 1E [aula DAD_]

motivazione della scelta: libero_altra_classe_stesso_gruppo

vecchio orario: -  -  -  -  -  (3T)  1A  4A
nuovo orario: -  -  1E [DAD_]  -  -  (3T)  1A  4A`

al posto delle ultime due righe dovrebbe comparire una tabella con una singola riga in cui l'ora della sostituzione deve comparire in rosso grassetto e più grande
![image](https://user-images.githubusercontent.com/44832441/105021867-5af43b80-5a49-11eb-959a-d0981fff15ee.png)

**Comment by SoftwareIISGubbio** [comment]
nell'orario devono comparire anche le ore di potenziamentoi che il docente già svolge.

Ad esempio selezionare "Giammarioli" poi il 22-1-2021 (venerdì), tra le sostituzioni scegliere la prima "cerquetelli": non compaiono le ore di potenziamento che svolge

**Comment by Yoshiro0990** [comment]
Rimosse e sostituite le ultime 2 righe con una tabella che mostra tutto l'orario modificato del sostituto e, in rosso, l'ora da sostituire.
Commit 012b8f7
