### ISSUE TITLE
Alcune sostituzioni non contano come recupero

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#55]
Bisogna inserire una spunta per permettere di non considerare come recuperate ad esempio le ore di copresenza o di potenziamento

**Comment by SoftwareIISGubbio** [comment]
Questa modifica impatta almeno su:
- interfaccia grafia
- oggetto sostituzione
- lettura/scrittura del giornale
- finestra delle statistiche

quando si salvano nel CSV bisogna metterle come ultima colonna per fare in modo che quando si legge il csv se l'ultima colonna manca si possa leggere lo stesso (e considerando l'ora come valida per il recupero)

**Comment by Yoshiro0990** [comment]
Aggiunta con il commit 1535ba9
