### ISSUE TITLE
impostare i colori delle sostituzioni nel foglio di stile

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#58]
it.edu.iisgubbio.sostituzioni.gui.CasellaSostituzione contiene un elenco di switch tipo

```
case copresenza:
    this.setStyle("-fx-background-color: #f7f7f7");
    break;
```

da valutare se si può semplicemente mettere una classe e poi impostare i colori dal foglio di stile

**Comment by Yoshiro0990** [comment]
Tutti i colori delle sostituzioni sono stati spostati sul foglio di stile con il commit d16e3e8
