### ISSUE TITLE
Filtro per ora prima/dopo un'ora lavorativa

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#68]
Serve un ulteriore filtro che se un professore lavora 2-3 ora consideri "buone" anche la prima e la quarta

Oppure se lavora 2 e 6 1,3,5 sono dispoibili

Devono comparire nella lista dopo le ore buche con i colori

#009975
#00ffc3
#99ffe7

**Comment by SoftwareIISGubbio** [comment]
Altri esempi:

Se il docente lavora 3-4 ora alora sono disponibili 2 e 5
Se il docente lavora 5 ora alora sono disponibili 4 e 6

**Comment by SoftwareIISGubbio** [comment]
Regola generale:
l'ora X può essere considerata utilizzabile "lavoraOraAdiacente" se:
non lavora nell'ora X ma lavora nell'ora X+1
non lavora nell'ora X ma lavora nell'ora X-1

**Comment by SoftwareIISGubbio** [comment]
Colori corretti
#99ffe7
#47ffd4
#02e3ae

**Comment by SoftwareIISGubbio** [comment]
Questo bug è da verificare e in caso da chiudere?

Sono stati fatti dei test?

**Comment by Yoshiro0990** [comment]
Aggiunto con il commit 525f3b0 e testato, in ritardo.
Chiudo il bug.
