### ISSUE TITLE
Spostare il menù per mostarre i problemi

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#70]
Eliminare il menu "Problemi" e aggiungere al menu "Strumenti" una voce "Mostra problemi" che apre la finestra "problemi dei dati" adesso raggiungibile dal sottomenu "mostra" di "Problemi"

**Comment by mariuccidiego** [comment]
bug risolto

**Comment by SoftwareIISGubbio** [comment]
il commit relativo alla soluzione è 35d854136072c050e7ab81e7a73e99f17ef4caed
