### ISSUE TITLE
Esportazione giornata

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#71]
Aggiungere un nuovo sub-menù "esporta giornata..." al menù "strumenti".
Alla selezione del menù deve comparire una finestra di dialogo che permette di scegliere una data e di confermare l'azione.
Alla conferma il programma salva nella stessa cartella dei biglietti un file chiamato "giornata-aa-mm-gg.xlsx" che contiene tutte le sostituzioni della giornata.

**Comment by SoftwareIISGubbio** [comment]
questo è il file di esempio: [esempio_file_assenti.xlsx](https://github.com/SoftwareIISGubbio/sostituzioni/files/9765509/esempio_file_assenti.xlsx)

I dati possono essere desunti dal giornale, potrebbe essere soluzione attualmente accettabile ri-leggere il giornale prima di generare questo file.

**Comment by mariuccidiego** [comment]
completato questo issue con il commit 204

**Comment by mariuccidiego** [comment]
il commit relativo alla soluzione è e208545fc9af0aec104629d38203692e5c2c900e

**Comment by SoftwareIISGubbio** [comment]
Il nome del file dovrebbe essere nel formato "giornata-aaaa-mm-gg.xlsx" questo perché in tal modo se ci sono molti file di questo tipo possono essere facilmente ordinati da gestione risorse o finder o simili. (la richiesta originale prevedeva due cifre per l'anno ma meglio scriverlo per intero)

**Comment by mariuccidiego** [comment]
il formato è gia "giornata-aaaa-mm-gg.xlsx" 
[mercoledì-2022-ottobre-19.xlsx](https://github.com/SoftwareIISGubbio/sostituzioni/files/9823161/mercoledi-2022-ottobre-19.xlsx)

**Comment by SoftwareIISGubbio** [comment]
in effetti fraintendibile... avevo messo un formato simile a quello di DateFormat, spiego meglio.
"mercoledì-2022-ottobre-19.xlsx" dovrebbe essere "giornata-2022-10-19.xlsx" questo perché si può ordinare facilmente, mettendo i nomi dei giorni o la data in altro modo si avrebbe ad esempio il seguente ordinamento:

> "lunedì-2022-ottobre-19.xlsx"
> "mercoledì-2023-ottobre-19.xlsx"
> "venerdì-2019-ottobre-19.xlsx"

**Comment by mariuccidiego** [comment]
sistemato il nome del file ora è "giornata-aaaa-mm-gg.xlsx",  con il commit 98f9eef3f2a1c06921b91f546ad5e80b47eb47e9
