### ISSUE TITLE
Miglioramenti estetici al file excel della giornata.

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#72]
Il file di esempio è solo per le prime ore ma tanto le altre sono analoghe.

In pratica: 
le intestazioni sono in grassetto 
la prima riga è anche gialla, rgb(238,205,0)
le colonne sono di dimensioni diverse (ovviamente a parità di dintestazione parità di larghezza)
la misura del font del motivo è più piccola

[martedì-2022-ottobre-18.xlsx](https://github.com/SoftwareIISGubbio/sostituzioni/files/9792602/martedi-2022-ottobre-18.xlsx)

**Comment by mariuccidiego** [comment]
Sistemato con il commit 3bf20abe3ea74e171eca5756e724af3789202bc0
