### ISSUE TITLE
Evidenziare funzionamento finestra "esporta giornata"

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/sostituzioni#74]
Per rendere più chiaro come si usa farebbe compudo un testo sopra la casella per scegliere l'ora che dice qualcosa del tipo "scegli la giornata da esportare"

Una volta esportata la giornata sarebbe utile se comparisse (sotto la casella di scelta? o altrove ma magari senza ulteriori finestre di dialogo) un messaggio del tipo "<data> salvata nel fil <nome dle file>"

**Comment by mariuccidiego** [comment]
Interfaccia sistemata con il commit 513c8c0cc10571c7c3a87b6f11fb16cfc9e4538f

**Comment by SoftwareIISGubbio** [comment]
Una volta che il file è stato salvato nell'interfaccia deve comprire qualcosa che indica che il lavoro è stato fatto, basta una stringa in una etichetta del tipo "data scritta in qualche modo, salvata nel file nome_del_file"

**Comment by mariuccidiego** [comment]
aggiunta nella finestra esporta giornata una label che quado clicchi "Esporta giornata" fa vedere il nome del file con il commit 1604d224071be93c2eed9093084a0323bc64caa1
